### ISSUE TITLE
`RatpackPac4j#requireAuth` should add `WWW-Authenticate` header on a 401

### ISSUE THREAD

**Issue by wu-lee** [pac4j/ratpack-pac4j#3]
I'm testing an app using the following versions in my gradle config:

```
    compile group: 'io.ratpack', name: 'ratpack-groovy', version: '1.5.4'
    compile group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.25'
//    compile ratpack.dependency('pac4j') // Don't use this, because we need the org.pac4j version
    compile group: 'org.pac4j', name: 'ratpack-pac4j', version: '2.0.0'
    compile group: 'org.pac4j', name: 'pac4j-core', version: '2.2.1'
    compile group: 'org.pac4j', name: 'pac4j-jwt', version: '2.2.1'
    compile group: 'org.pac4j', name: 'pac4j-http', version: '2.2.1'
```
I find that when I use this handler:

    all RatpackPac4j.requireAuth(HeaderClient)

Unauthorized requests get rejected correctly with a 401 status, but I believe a `WWW-Authenticate: ...` header should be added, and it is not.

Checking the source code leads me to suspect `RatpackPac4j#login`, which sets the 401 code, but does not add this header:

```
  public static <C extends Credentials, U extends CommonProfile> Promise<U> login(Context ctx, Class<? extends Client> clientType) {
    if (isDirect(clientType)) {
      return userProfile(ctx)
        .flatMap(p -> {
          if (p.isPresent()) {
            Optional<U> cast = Types.cast(p);
            return Promise.value(cast);
          } else {
            return performDirectAuthentication(ctx, clientType);
          }
        })
        .route(p -> !p.isPresent(), p -> ctx.clientError(401))
        .map(Optional::get);
    } else {
      return userProfile(ctx)
        .route(p -> !p.isPresent(), p -> initiateAuthentication(ctx, clientType))
        .map(Optional::get)
        .map(Types::<U>cast);
    }
```

Thanks!

**Comment by gregopet** [comment]
Are you using the direct or indirect client? This might very well be a bug in Pac4j, I've also been weirded out by this behaviour.

If I understand everything correctly, the direct client will not issue any redirects or authentication requests _by design_, while the indirect client will _always redirect_ the request, no matter what authentication method is used, and then the redirection target will actually add the `WWW-Authenticate` header.

I've always thought this was a result of how Pac4j is designed (i.e. that it doesn't want to handle 'special' cases such which are kind of in between their direct/indirect concepts), but if it can be solved without rewriting the Pac4j internal architecture I'd also love to know!

**Comment by wu-lee** [comment]
Do you mean "client" or "server"? (This is server-side logic, no?)

The client I'm using is Ratpack's `ServerBackedApplicationUnderTest` http client (it's in a test case). If it got an unhandled redirect back I believe I'd see it in the response, and I don't.

The server is of course Ratpack (v1.5.4)

**Comment by leleuj** [comment]
@gregopet You get it right: with the direct client, no header is added while it is with the indirect basic auth client. For short, it was developed this way by design.
That said, the design of pac4j must obey the specs and the HTTP spec says the header is always mandatory so this is "fixed" in pac4j v3.

Nonetheless, ratpack-pac4j has not been upgraded to pac4j v3 yet.
