### ISSUE TITLE
Pac4j stateless authentication

### ISSUE THREAD

**Issue by timic** [pac4j/ratpack-pac4j#4]
Ratpack-pac4j integration strictly bounds to HTTP session. This is not eligible for implementing stateless RESTful API. 

Referring to [pac4j documentation](http://www.pac4j.org/docs/clients.html#1-direct-vs-indirect-clients) we should cache `UserProfile` using `LocalCachingAuthenticator` and use this approach as default behavior for all "direct clients".

**Comment by timic** [comment]
Copy [of](https://github.com/ratpack/ratpack/issues/1193).

**Comment by leleuj** [comment]
So far, I haven't done more in this project than following the official one (with some breaking changes upgrades). I just found out that pac4j has been marked deprecated by the Ratpack project and asked for explanations, we'll see...

**Comment by leleuj** [comment]
I got an explanation and this module will take over the original one in Ratpack. So we can start making it evolve without worrying about the original one.
This module has a rather specific implementation (it's not exactly built like other pac4j implementations).

What's your proposal to deal with direct clients?

**Comment by leleuj** [comment]
Closed due to inactivity.
